config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

    get 'users/:id' => 'users#show'
    get 'users/index' => 'users#index'

    get 'bids/index' => 'bids#index'
    get 'bids/create' => 'bids#create'
    get 'bids/show' => 'bids#show'

    get 'items/show' => 'items#show'

end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :user
	belongs_to :item

	validates :user_id, :item_id
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :bids
	has_many :users, through: :bids

	validates :item_name, :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :bids
	has_many :items, through: :bids

	validates :username, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/' unless current_user
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
	#again, authorize login before allowing them to place bids
	before_filter :authorize
	#bids index also only available for admin to see macro data
	def index
	end

###################################################################################

	#show the result of a bid - conditional for win or lose based on RNG
	def show
	end
	
	#no bid#new route since that page is covered by the item - show page, which redirects to bid#create

	#create route redirects to the show page which has the result
	def create
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	#this before will allow you to pull up the barcode scanner, but before you can actually see the item (and possibly bid), you must log in
	before_filter :authorize

	#this serves the purpose of the bid#new route as well, shows item details and button to bid
	def show
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by email:(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to action: 'welcome', controller: 'users'
  	else
  		redirect_to '/login'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#list of all users for admin only
	def index
	end

###################################################################################

	#landing page for the app - instructions and pull up barcode scanner button
	def welcome
	end

	#user profile page - items bid, items won, etc
	def show
	end

	def new
	end

	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
      redirect_to action: 'welcome', controller: 'users'
		else
			@errors = user.errors.full_messages
			render '/users/new'
		end
	end

	private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CirkleBackend</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Signup!</h1>

<% if @errors %>
	<% @errors.each do |error| %>
		<p><%= error %></p>
	<% end  %>
<% end %>

<%= form_for :user, url: '/users' do |f| %>

  Username: <%= f.text_field :username %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/welcome.html.erb
<h1>Welcome to Cirkle!</h1>

<% if current_user %>
	<%= link_to 'Log Out', logout_path %>
	<h3>Hi, <%= current_user.username %></h3>
<% else %>
	<%= link_to 'Login', login_path %>
	<%= link_to 'Register', signup_path %>
<% end %>